# Generated by Django 4.0.6 on 2024-07-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('bautismo', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Publicador',
                'verbose_name_plural': 'Publicadores',
            },
        ),
    ]
